In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load websites data

websites = pd.read_csv("websites.csv")

In [3]:
# display the first few rows

websites.head()

     website  visitors  bounces
0  website 1      1000      300
1  website 2       800      150
2  website 3      1200      200
3  website 4      1500      400
4  website 5       900      270

In [4]:
# get some basic information

websites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   website   50 non-null     object
 1   visitors  50 non-null     int64
 2   bounces   50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [5]:
# calculate bounce rate as a percentage and add as a new column

websites["bounce_rate"] = (websites["bounces"] / websites["visitors"]) * 100

In [6]:
# view the updates

websites

       website  visitors  bounces  bounce_rate
0    website 1      1000      300    30.000000
1    website 2       800      150    18.750000
2    website 3      1200      200    16.666667
3    website 4      1500      400    26.666667
4    website 5       900      270    30.000000
5    website 6      1100       90     8.181818
6    website 7      1300      180    13.846154
7    website 8       950       80     8.421053
8    website 9      1150      130    11.304348
9   website 10      1050       70     6.666667
10  website 11      1400      200    14.285714
11  website 12       850       60     7.058824
12  website 13      1100      100     9.090909
13  website 14      1000       90     9.000000
14  website 15      1200      120    10.000000
15  website 16      1300      160    12.307692
16  website 17      1000       70     7.000000
17  website 18       800       40     5.000000
18  website 19      1200      110     9.166667
19  website 20      1500      180    12.000000
20  website 21       950       70     7.368421
21  website 22      1150      120    10.434783
22  website 23      1050       80     7.619048
23  website 24      1400      220    15.714286
24  website 25       900      100    11.111111
25  website 26      1100      140    12.727273
26  website 27      1300      200    15.384615
27  website 28       950       80     8.421053
28  website 29      1150      100     8.695652
29  website 30      1050       90     8.571429
30  website 31      1400      180    12.857143
31  website 32       850       50     5.882353
32  website 33      1100       80     7.272727
33  website 34      1000       70     7.000000
34  website 35      1200       90     7.500000
35  website 36      1300      160    12.307692
36  website 37      1000       70     7.000000
37  website 38       800       40     5.000000
38  website 39      1200      110     9.166667
39  website 40      1500      180    12.000000
40  website 41       950       70     7.368421
41  website 42      1150      120    10.434783
42  website 43      1050       80     7.619048
43  website 44      1400      220    15.714286
44  website 45       900      100    11.111111
45  website 46      1100      140    12.727273
46  website 47      1300      200    15.384615
47  website 48       950       80     8.421053
48  website 49      1150      100     8.695652
49  website 50      1050       90     8.571429