In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv into dataframe

data = pd.read_csv("pages_clicked.csv")

In [4]:
# display the first few rows of the data

data.head()

,Page,Clicks,Impressions,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews
0,Page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095
1,Page 2,80,30824,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181
2,Page 3,16,1458,30.64,0 days 00:04:06.000000000,53.335000,89.475000,30,26
3,Page 4,11,517,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21
4,Page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890000,15,13

In [5]:
# display basic information about the data

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Page               193 non-null    object
 1   Clicks             193 non-null    int64
 2   Impressions        193 non-null    int64
 3   Position           193 non-null    float64
 4   Avg. Time on Page  193 non-null    object
 5   Bounce Rate        193 non-null    float64
 6   Exit               193 non-null    float64
 7   Pageviews          193 non-null    int64
 8   Unique Pageviews   193 non-null    int64
dtypes: float64(3), int64(4), object(2)
memory usage: 13.7+ KB

In [6]:
# calculate click-through rate (CTR) as a percentage and add as a new column

data["CTR"] = (data["Clicks"] / data["Impressions"]) * 100

In [7]:
# view the updates

data

,Page,Clicks,Impressions,Position,Avg. Time on Page,Bounce Rate,Exit,Pageviews,Unique Pageviews,CTR
0,Page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095,0.368520
1,Page 2,80,30824,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181,0.259538
2,Page 3,16,1458,30.64,0 days 00:04:06.000000000,53.335000,89.475000,30,26,1.097394
3,Page 4,11,517,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21,2.127660
4,Page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890000,15,13,7.142857
...,...,...,...,...,...,...,...,...,...,...
188,Page 189,0,2,51.00,0 days 00:00:00.000000000,100.000000,100.000000,1,1,0.000000
189,Page 190,0,2,74.00,0 days 00:00:00.000000000,100.000000,100.000000,1,1,0.000000
190,Page 191,0,1,1.00,0 days 00:04:32.500000000,71.430000,93.750000,9,8,0.000000
191,Page 192,0,1,4.00,0 days 00:03:47.000000000,0.000000,0.000000,2,1,0.000000
192,Page 193,0,1,5.00,0 days 00:00:10.000000000,0.000000,0.000000,1,1,0.000000