In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

data = pd.read_csv("analytics_search_data.csv")

In [3]:
# view first few rows of data

data.head()

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
0,page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095
1,page 2,80,30824,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181
2,page 3,16,1458,30.64,0 days 00:04:06.000000000,53.335000,89.475000,30,26
3,page 4,11,517,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21
4,page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890000,15,13

In [4]:
# filter and sort the data

# filter the data by pages that have received 100 or more impressions, then sort by exit rate in ascending order, then save resulting dataframe in a variable

filtered_data = data[data["impressions"] >= 100].sort_values(by="exit_rate", ascending=True)

In [5]:
# view first few rows of filtered_data

filtered_data.head()

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
36,page 37,1,115,26.13,0 days 00:00:02.000000000,0.000000,0.000,1,1
84,page 85,0,400,27.06,0 days 00:00:26.500000000,50.000000,33.335,6,6
4,page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890,15,13
83,page 84,0,779,105.60,0 days 00:00:21.000000000,25.000000,41.665,5,5
32,page 33,1,203,54.72,0 days 00:05:13.500000000,50.000000,50.000,4,4

In [6]:
# export the filtered_data to a CSV file which will populate into your local file system

filtered_data.to_csv("filtered_data.csv", index=False)