In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

data = pd.read_csv("analytics_search_data.csv")

In [3]:
# view first few rows

data.head()

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
0,page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095
1,page 2,80,30824,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181
2,page 3,16,1458,30.64,0 days 00:04:06.000000000,53.335000,89.475000,30,26
3,page 4,11,517,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21
4,page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890000,15,13

In [4]:
# filter the data by pages that have received 100 or more clicks

data[data["clicks"] >= 100]

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
0,page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095

In [5]:
# filter the data by pages that have received 100 or more clicks, extracting a subset of columns

data.loc[data["clicks"] >= 100, ["page", "clicks", "impressions", "unique_views"]]

     page  clicks  impressions  unique_views
0  page 1     371       100673          1095

In [6]:
# filter with multiple conditions

# filter the data by pages that have received 100 or more impressions *and* position 10 or less

data[(data["impressions"] >= 100) & (data["position"] <= 10)]

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
4,page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.89,15,13
14,page 15,3,227,7.59,0 days 00:00:00.000000000,0.000000,100.00,4,4
34,page 35,1,166,8.00,0 days 00:00:00.000000000,0.000000,100.00,1,1

In [7]:
# filter and sort the data

# filter the data by pages that have received 100 or more impressions, then sort by exit rate in ascending order

data[data["impressions"] >= 100].sort_values(by="exit_rate", ascending=True)

,page,clicks,impressions,position,avg_time,bounce_rate,exit_rate,views,unique_views
36,page 37,1,115,26.13,0 days 00:00:02.000000000,0.000000,0.000000,1,1
84,page 85,0,400,27.06,0 days 00:00:26.500000000,50.000000,33.335000,6,6
4,page 5,10,140,5.61,0 days 00:02:52.000000000,22.223333,38.890000,15,13
83,page 84,0,779,105.60,0 days 00:00:21.000000000,25.000000,41.665000,5,5
32,page 33,1,203,54.72,0 days 00:05:13.500000000,50.000000,50.000000,4,4
30,page 31,1,342,69.30,0 days 00:05:44.500000000,50.000000,50.000000,4,3
18,page 19,2,441,42.23,0 days 00:00:21.500000000,50.000000,50.000000,2,2
90,page 91,0,238,49.63,0 days 00:00:27.333333333,38.890000,53.786667,24,24
0,page 1,371,100673,42.59,0 days 00:01:43.666666666,47.296667,54.286667,1396,1095
87,page 88,0,328,71.85,0 days 00:00:40.333333333,83.333333,58.170000,21,16
8,page 9,5,4177,70.02,0 days 00:01:31.666666666,61.906667,60.256667,198,160
1,page 2,80,30824,26.84,0 days 00:01:45.333333333,64.436667,60.913333,210,181
82,page 83,0,1496,215.61,0 days 00:00:32.500000000,100.000000,66.665000,4,4
28,page 29,1,447,72.25,0 days 00:02:09.000000000,0.000000,66.670000,3,2
7,page 8,6,401,17.84,0 days 00:00:14.000000000,66.670000,66.670000,9,6
9,page 10,5,263,46.38,0 days 00:02:04.000000000,50.000000,67.855000,9,9
12,page 13,3,323,57.47,0 days 00:00:05.500000000,25.000000,70.000000,7,5
21,page 22,2,149,38.76,0 days 00:00:53.000000000,50.000000,75.000000,5,3
96,page 97,0,123,56.71,0 days 00:00:10.500000000,50.000000,75.000000,3,3
29,page 30,1,385,41.75,0 days 00:07:23.000000000,46.970000,76.225000,24,19
10,page 11,4,203,41.95,0 days 00:00:44.666666666,59.310000,77.920000,63,60
3,page 4,11,517,36.05,0 days 00:00:22.333333333,58.170000,78.333333,27,21
6,page 7,7,226,38.91,0 days 00:00:11.000000000,83.330000,85.710000,7,6
15,page 16,3,142,55.27,0 days 00:18:09.500000000,50.000000,87.500000,5,5
2,page 3,16,1458,30.64,0 days 00:04:06.000000000,53.335000,89.475000,30,26
91,page 92,0,150,52.40,0 days 00:00:00.000000000,100.000000,100.000000,1,1
94,page 95,0,133,18.98,0 days 00:00:00.000000000,0.000000,100.000000,1,1
93,page 94,0,139,57.86,0 days 00:00:00.000000000,100.000000,100.000000,1,1
89,page 90,0,251,44.64,0 days 00:00:00.000000000,0.000000,100.000000,1,1
88,page 89,0,279,47.51,0 days 00:00:00.000000000,100.000000,100.000000,1,1
95,page 96,0,125,52.12,0 days 00:00:00.000000000,100.000000,100.000000,1,1
86,page 87,0,372,32.97,0 days 00:00:00.000000000,0.000000,100.000000,1,1
92,page 93,0,147,76.59,0 days 00:00:00.000000000,100.000000,100.000000,2,2
31,page 32,1,281,43.88,0 days 00:00:00.000000000,100.000000,100.000000,1,1
37,page 38,1,100,44.44,0 days 00:00:00.000000000,0.000000,100.000000,1,1
35,page 36,1,126,44.63,0 days 00:00:00.000000000,100.000000,100.000000,1,1
34,page 35,1,166,8.00,0 days 00:00:00.000000000,0.000000,100.000000,1,1
33,page 34,1,193,19.16,0 days 00:00:00.000000000,100.000000,100.000000,1,1
97,page 98,0,106,21.00,0 days 00:00:00.000000000,100.000000,100.000000,1,1
20,page 21,2,151,39.14,0 days 00:00:00.000000000,50.000000,100.000000,3,3
19,page 20,2,172,79.20,0 days 00:00:00.000000000,0.000000,100.000000,1,1
14,page 15,3,227,7.59,0 days 00:00:00.000000000,0.000000,100.000000,4,4
13,page 14,3,322,29.38,0 days 00:00:00.000000000,100.000000,100.000000,2,2
11,page 12,4,129,22.84,0 days 00:00:00.000000000,100.000000,100.000000,3,3
5,page 6,7,442,74.55,0 days 00:00:00.000000000,100.000000,100.000000,3,3
85,page 86,0,377,65.40,0 days 00:00:00.000000000,0.000000,100.000000,2,2
98,page 99,0,101,24.12,0 days 00:00:00.000000000,100.000000,100.000000,3,3