In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

data = pd.read_csv("channels.csv")

In [3]:
# view first few rows

data.head()

   Channel Region  Sales  Clicks
0   Online  North   1500     500
1  Offline  South   2300     700
2   Online   East   1800     600
3  Offline   West   2100     550
4  Offline  North   2500     800

In [4]:
# get some basic information

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Channel  100 non-null    object
 1   Region   100 non-null    object
 2   Sales    100 non-null    int64
 3   Clicks   100 non-null    int64
dtypes: int64(2), object(2)
memory usage: 3.3+ KB

In [5]:
# group data by "Channel" and get average "Sales" per group 

data[["Channel", "Sales"]].groupby("Channel").mean()

               Sales
Channel
Offline  1792.156863
Online   2540.816327

In [6]:
# group data by "Region" and get average "Sales" per group 

data[["Region", "Sales"]].groupby("Region").mean()

         Sales
Region
East    1968.0
North   2852.0
South   1388.0
West    2428.0

In [7]:
# group data by "Channel" and "Region" and get average "Sales" and average "Clicks" per group 

data.groupby(["Channel", "Region"]).mean()

                      Sales      Clicks
Channel Region
Offline East    1777.777778  698.888889
        North   2828.571429  985.714286
        South   1410.526316  721.578947
        West    1828.571429  632.857143
Online  East    2457.142857  767.142857
        North   2861.111111  940.000000
        South   1316.666667  743.333333
        West    2661.111111  840.555556

In [8]:
# group data by "Channel" and "Region" and get total "Sales" and total "Clicks" per group 

data.groupby(["Channel", "Region"]).sum()

                Sales  Clicks
Channel Region
Offline East    32000   12580
        North   19800    6900
        South   26800   13710
        West    12800    4430
Online  East    17200    5370
        North   51500   16920
        South    7900    4460
        West    47900   15130