In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

campaigns = pd.read_csv("campaigns.csv", parse_dates=["Reporting starts", "Reporting ends"])

In [3]:
# display the first few rows of campaigns

campaigns.head()

,Reporting starts,Reporting ends,Campaign,Delivery,Mobile app installs,Mobile app actions,Cost per mobile app install,Cost per mobile app action,Desktop app installs,Desktop app engagement,Cost per desktop app install,Cost per desktop app engagement,Post reactions,Post comments,Post shares
0,2014-02-21,2018-01-29,1,0,11451.0,NaN,1.275683,NaN,NaN,NaN,NaN,NaN,1807.0,42.0,133.0
1,2015-10-17,2015-10-17,4,inactive,26.0,NaN,1.269231,NaN,NaN,NaN,NaN,NaN,91.0,NaN,NaN
2,2015-10-18,2015-10-18,4,inactive,30.0,NaN,1.100000,NaN,NaN,NaN,NaN,NaN,71.0,NaN,NaN
3,2015-10-19,2015-10-19,4,inactive,17.0,NaN,0.882353,NaN,NaN,NaN,NaN,NaN,27.0,1.0,NaN
4,2015-08-14,2015-08-14,29,inactive,24.0,NaN,1.375000,NaN,NaN,NaN,NaN,NaN,20.0,NaN,3.0

In [4]:
# count the number of missing values per column

campaigns.isna().sum()

Reporting starts                      0
Reporting ends                        0
Campaign                              0
Delivery                              0
Mobile app installs                 679
Mobile app actions                 1381
Cost per mobile app install         679
Cost per mobile app action         1381
Desktop app installs               1381
Desktop app engagement             1381
Cost per desktop app install       1381
Cost per desktop app engagement    1381
Post reactions                      953
Post comments                      1343
Post shares                        1276
dtype: int64

In [5]:
# count how many rows have missing values

len(campaigns) - len(campaigns.dropna())

1381

In [6]:
# total rows

len(campaigns)

1381

In [7]:
# fill missing values with zero, in place

campaigns.fillna(0, inplace=True)

# display first few rows of campaigns after the update

campaigns.head()

,Reporting starts,Reporting ends,Campaign,Delivery,Mobile app installs,Mobile app actions,Cost per mobile app install,Cost per mobile app action,Desktop app installs,Desktop app engagement,Cost per desktop app install,Cost per desktop app engagement,Post reactions,Post comments,Post shares
0,2014-02-21,2018-01-29,1,0,11451.0,0.0,1.275683,0.0,0.0,0.0,0.0,0.0,1807.0,42.0,133.0
1,2015-10-17,2015-10-17,4,inactive,26.0,0.0,1.269231,0.0,0.0,0.0,0.0,0.0,91.0,0.0,0.0
2,2015-10-18,2015-10-18,4,inactive,30.0,0.0,1.100000,0.0,0.0,0.0,0.0,0.0,71.0,0.0,0.0
3,2015-10-19,2015-10-19,4,inactive,17.0,0.0,0.882353,0.0,0.0,0.0,0.0,0.0,27.0,1.0,0.0
4,2015-08-14,2015-08-14,29,inactive,24.0,0.0,1.375000,0.0,0.0,0.0,0.0,0.0,20.0,0.0,3.0