In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

analytics_data = pd.read_csv("analytics_data.csv")

In [3]:
# view the data that's been loaded in

analytics_data.head()

,URL,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value
0,example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00

In [4]:
# get basic information about analytics_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   URL                377 non-null    object
 1   Pageviews          377 non-null    int64
 2   Unique Pageviews   377 non-null    int64
 3   Avg. Time on Page  377 non-null    object
 4   Entrances          377 non-null    int64
 5   Bounce Rate        377 non-null    object
 6   % Exit             377 non-null    object
 7   Page Value         377 non-null    object
dtypes: int64(3), object(5)
memory usage: 23.7+ KB

In [5]:
# get descriptive statistics about analytics_data

        Pageviews  Unique Pageviews   Entrances
count  377.000000        377.000000  377.000000
mean     8.461538          6.586207    4.819629
std     53.620804         41.454520   38.351806
min      1.000000          1.000000    0.000000
25%      1.000000          1.000000    1.000000
50%      1.000000          1.000000    1.000000
75%      2.000000          2.000000    2.000000
max    813.000000        665.000000  641.000000

In [6]:
# examine a single row from analytics_data

URL                  example16.com
Pageviews                       19
Unique Pageviews                15
Avg. Time on Page          0:08:12
Entrances                       15
Bounce Rate                  6.67%
% Exit                      78.95%
Page Value                   $0.00
Name: 15, dtype: object