In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv files into dataframes 

users = pd.read_csv("users.csv")

analytics_data = pd.read_csv("analytics_data.csv")

In [3]:
# view the data that's been loaded in

users.head()

  Day Index  Users
0   8/31/18      5
1    9/1/18      4
2    9/2/18      5
3    9/3/18      3
4    9/4/18      4

In [4]:
# view the data that's been loaded in

analytics_data.head()

,URL,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value
0,example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00