In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv files into dataframes

search_data = pd.read_csv("search_data.csv")

analytics_data = pd.read_csv("analytics_data_updated.csv")

In [3]:
# view first few rows

search_data.head()

                    url  clicks  impressions  position
0  https://example1.com     371       100673     42.59
1  https://example2.com      80        30824     26.84
2  https://example3.com      16         1458     30.64
3  https://example4.com      11          517     36.05
4  https://example5.com      10          140      5.61

In [4]:
# view first few rows

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0 days 00:02:05,641,14.35,55.97,0.0
1,https://example2.com,515,388,0 days 00:02:17,373,59.25,56.89,0.0
2,https://example3.com,336,163,0 days 00:01:06,23,10.53,33.04,0.0
3,https://example4.com,140,120,0 days 00:02:04,73,18.31,57.86,0.0
4,https://example5.com,136,105,0 days 00:01:30,22,14.29,47.79,0.0

In [6]:
# merge the two dataframes
# save the resulting dataframe in a new variable

merged_data = pd.merge(search_data, analytics_data, how="inner", left_on="url", right_on="url")

# check out the result

merged_data.head()

,url,clicks,impressions,position,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,371,100673,42.59,813,665,0 days 00:02:05,641,14.35,55.97,0.0
1,https://example2.com,80,30824,26.84,515,388,0 days 00:02:17,373,59.25,56.89,0.0
2,https://example3.com,16,1458,30.64,336,163,0 days 00:01:06,23,10.53,33.04,0.0
3,https://example4.com,11,517,36.05,140,120,0 days 00:02:04,73,18.31,57.86,0.0
4,https://example5.com,10,140,5.61,136,105,0 days 00:01:30,22,14.29,47.79,0.0